apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "redisapp"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "redisapp"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: rediscontainername
          image: "redis:latest"
          imagePullPolicy: IfNotPresent