global:
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  redis:
    host: redis.external-services 
    password: ""
  vault:
    endpoint: vault.vault:8200
  
outputTopicPrefix: raw
dlqTopic: streaming-dead-letters
replicaCount: 1
metadata:
  labels:
image:
  repository: smartcitiesdata/reaper
  tag: development
  pullPolicy: Always
service:
  port: 9092
  type: ClusterIP

aws:
  region: us-west-2
  hostedFileBucket: ""

profiling_enabled: false

resources:
  limits:
    memory: 1Gi
    cpu: 300m
    ephemeral-storage: 15G
  requests:
    memory: 1Gi
    cpu: 300m
    ephemeral-storage: 15G

monitoring:
  targetPort: 9002
