service:
  name: discovery-ui
  type: NodePort
  port: 80

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  security_groups: "" #Load balancer Security Group
  dns_zone: "localhost"
  root_dns_zone: "localhost"
  certificate_arns: ""
  waf_acl_arn: ""
  tags: ""

image:
  name: smartcitiesdata/discovery_ui
  tag: development
  environment: "local"

env:
  api_host: "https://data.example.com"
  #contribute_host: "https://sharedata.example.com" #Optional location for an associated public Andi deployment
  gtm_id: "GTM-EXAMPLE"
  base_url: "example.com"
  streets_tile_layer_url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  mapbox_access_token: ""
  auth0_domain: ""
  auth0_client_id: ""
  auth0_audience: ""
  additional_csp_hosts: ""

nodeSelector: {}

tolerations: []

affinity: {}
