{{- if .Values.secrets.live_view.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: estuary-lv-salt
type:
  Opaque
data:
  salt: ZGV2X29ubHlfZW5hYmxlX2ZhbHNlX2FuZF9kZWZpbmVfb3V0X29mX3NvdXJjZV9pbl9wcm9kCg==
  # salt: {{ .Values.secrets.live_view.value }}
{{- end }}
