dependencies:
  - name: forklift
    version: 3.0.0
    repository: https://Datastillery.github.io/charts
    condition: forklift.enabled
  - name: odo
    version: 1.0.0
    repository: https://Datastillery.github.io/charts
    condition: odo.enabled
  - name: reaper
    version: 1.0.0
    repository: https://Datastillery.github.io/charts
    condition: reaper.enabled
  - name: valkyrie
    version: 2.6.0
    repository: https://Datastillery.github.io/charts
    condition: valkyrie.enabled
  - name: andi
    version: 2.0.0
    repository: https://Datastillery.github.io/charts
    condition: andi.enabled
  - name: external-services
    version: 1.0.0
    repository: https://Datastillery.github.io/charts
    condition: external-services.enabled