global:
  aws:
    region: us-west-2
  buckets:
    hostedFileBucket: ""
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  presto:
    url: http://kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services
    password: ""
  vault:
    endpoint: vault.vault:8200
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
      alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
      alb.ingress.kubernetes.io/scheme: "internal"
      alb.ingress.kubernetes.io/subnets: ""
      alb.ingress.kubernetes.io/security-groups: ""
      alb.ingress.kubernetes.io/certificate-arn: ""
      alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
      alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/wafv2-acl-arn: ""
    dnsZone: ""
    rootDnsZone: ""
    port: 80

forklift:
  fullnameOverride: forklift
  enabled: true
reaper:
  fullnameOverride: reaper
  enabled: true
valkyrie:
  fullnameOverride: valkyrie
  enabled: true
  replicaCount: 1
odo:
  enabled: true
andi:
  fullnameOverride: andi
  enabled: true
kafka:
  enabled: true

kubernetes-data-platform:
  enabled: true
  presto:
    workers: 2
    jvm:
      maxHeapSize: 1536M
    deploy:
      container:
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
    task:
      writerCount: 1
    deployPrometheusExporter: true
    useJmxExporter: true
  metastore:
    allowDropTable: true
    timeout: 360m
  postgres:
    enable: false
    db:
      name: metastore
      user: metastore
    tls:
      enable: true
      mode: verify-full
      rootCertPath: /etc/ssl/certs/ca-certificates.crt
  minio:
    enable: false
