replicaCount: 1
image:
  repository: smartcitiesdata/odo
  tag: development
  pullPolicy: Always

redis:
  host: redis.external-services

kafka:
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

vault:
  endpoint: http://vault.vault:8200

cloud:
  region: us-east-1
  fileBucket: ""

resources:
  limits:
    memory: 2Gi
    cpu: 300m
  requests:
    memory: 2Gi
    cpu: 300m

prometheus:
  scrape: true
  metrics_port: 9002
