replicaCount: 3

service:
  name: discovery-api
  type: NodePort
  port: 80
  auth_string: ""

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  security_groups: ""
  dnsZone: "localhost"
  rootDnsZone: "localhost"
  certificate_arn: ""

image:
  name: smartcitiesdata/discovery_api
  tag: development
  pullPolicy: IfNotPresent

monitoring:
  targetPort: 9002

nodeSelector: {}
tolerations: []
affinity: {}

presto:
  url: "http://presto-endpoint:8080"
  catalog: "hive"
  schema: "default"

ldap:
  host: "ldap.example.com"
  base: "dc=example,dc=com"
  user: "binduser"
  account:
    subdn: "cn=users,cn=accounts"

s3:
  hostedFileBucket: "hosted-dataset-files"
  hostedFileRegion: "us-west-2"

vault:
  endpoint: vault.vault:8200

postgres:
  host: "example.com"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"

elasticsearch:
  host: "es.example.com"

auth:
  domain: "example.com"
  client_id: "1234"
  redirect_base_url: "http://localhost"
  jwks_endpoint: "https://example.com/.well-known/jwks.json"
  jwt_issuer: "https://example.com/"
  user_info_endpoint: "https://example.com/userinfo"

secrets:
    discoveryApiPresignKey: ""
