presto:
  user: "estuary"
  url: "http://kdp-kubernetes-data-platform-presto.kdp:8080"

kafka:
  #comma delimited list of kafka seed brokers
  brokers: data-broker:9092

estuary:
  data_topic: streaming-persisted
  table_name: "event_stream"

image:
  repository: smartcitiesdata/estuary
  tag: development
  pullPolicy: IfNotPresent

# defaults to be overridden by user
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
