apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | trim | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ .Release.Name }}
    servicePort: {{ .Values.service.port }}
  rules:
  {{- range .Values.ingress.rules }}
  - host: "{{ .hostPrefix | default $.Release.Name }}.{{ .dnsZone }}"
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  {{- end }}
  
