apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    prometheus.io/port:  "{{ .Values.monitoring.targetPort }}"
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: NodePort
