dashboard:
  title: "Dashboard Metrics"

image:
  repository: smartcitiesdata/discovery_streams
  tag: development
  pullPolicy: Always

replicaCount: 1

monitoring:
  targetPort: 9002

service:
  type: NodePort
  port: 80
  targetPort: 4000

ingress:
  annotations: