replicaCount: 1

image:
  repository: smartcitiesdata/forklift
  tag: development
  pullPolicy: Always

service:
  type: ClusterIP

kafka:
  #comma delimited list of kafka seed brokers
  brokers: data-broker:9092
  strimziCluster: streaming-service
  dataTopicPrefix: "transformed"
  outputTopic: "streaming-persisted"

nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}

kdp:
  user: "forklift"
  url: http://presto-endpoint:8080

redis:
  host: forklift-redis-master
  password: ""

monitoring:
  targetPort: 9002

profiling_enabled: false

# Dataset compaction is off by default. If it is needed, set compactionSchedule to a valid cron string such as "00 01 * * *" (This will run compaction nightly at 1:00am)
compactionSchedule: null
# Special compaction datasets use the variant compaction introduced in https://github.com/Datastillery/smartcitiesdata/pull/950
# This is a comma seperated list of dataset ids, and will only be used if a compactionSchedule is provided. WARNING: tables will be mutated to enable the variant compaction process
specialCompactionDatasets: null
