apiVersion: v1
kind: Secret
metadata:
  name: ldap
type: Opaque
data:
  host: bGRhcC1vcGVubGRhcA== # ldap-openldap
  base_dn: ZGM9ZXhhbXBsZSxkYz1vcmc= # dc=example,dc=org
  user: Y249YWRtaW4= # cn=admin
  password: VGhpc0lzNG40ZG1pblA0c3N3b3Jk # ThisIs4n4dminP4ssword
  environment_ou: b3Jncw== # orgs