dependencies:
  - name: redis
    version: 9.5.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: openldap
    version: 1.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: openldap.enabled
  - name: strimzi-kafka-operator
    version: 0.13.0
    repository: https://strimzi.io/charts
    condition: strimzi-kafka-operator.enabled
  - name: andi
    version: 1.1.2
    repository: https://smartcitiesdata.github.io/charts
    condition: andi.enabled
  - name: discovery-api
    version: 0.4.2
    repository: https://smartcitiesdata.github.io/charts
    condition: discovery-api.enabled
  - name: discovery-streams
    version: 0.1.4
    repository: https://smartcitiesdata.github.io/charts
    condition: discovery-streams.enabled
  - name: discovery-ui
    version: 0.2.3
    repository: https://smartcitiesdata.github.io/charts
    condition: discovery-ui.enabled
  - name: forklift
    version: 2.4.0
    repository: https://smartcitiesdata.github.io/charts
    condition: forklift.enabled
  - name: kubernetes-data-platform
    version: 1.0.0
    repository: https://smartcitiesdata.github.io/charts
  - name: reaper
    version: 0.1.1
    repository: https://smartcitiesdata.github.io/charts
    condition: reaper.enabled
  - name: valkyrie
    version: 2.4.0
    repository: https://smartcitiesdata.github.io/charts
    condition: valkyrie.enabled
