apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "odo.chart" . }}
    app.kubernetes.io/name: {{ include "odo.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceAccountName: odo
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "odo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "odo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /downloads
          name: download-dir
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
      volumes:
      - name: download-dir
        emptyDir: {}
