apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: discovery
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
          - name: "API_HOST"
            value: {{ .Values.env.api_host }}
          - name: "GTM_ID"
            value: {{ .Values.env.gtm_id }}
          - name: "BASE_URL"
            value: {{ .Values.env.base_url }}
          - name: "STREETS_TILE_LAYER_URL"
            value: {{ .Values.env.streets_tile_layer_url }}
          - name: "LOGO_URL"
            value: {{ .Values.env.logo_url | default "null" }}
          - name: "MAPBOX_ACCESS_TOKEN"
            value: {{ .Values.env.mapbox_access_token }}
          - name: "AUTH0_DOMAIN"
            value: {{ .Values.env.auth0_domain }}
          - name: "AUTH0_CLIENT_ID"
            value: {{ .Values.env.auth0_client_id }}
