apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  ports:
  - protocol: TCP
    port: 80
  type: "{{ .Values.service.type }}"
