dependencies:
  - name: forklift
    repository: file://../forklift
    condition: forklift.enabled
  - name: odo
    repository: file://../odo
    condition: odo.enabled
  - name: reaper
    repository: file://../reaper
    condition: reaper.enabled
  - name: valkyrie
    repository: file://../valkyrie
    condition: valkyrie.enabled