global:
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  presto:
    url: http://platform-kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services 
    password: ""
  vault:
    endpoint: vault.vault:8200

forklift:
  fullnameOverride: forklift
  enabled: true
reaper:
  fullnameOverride: reaper
  enabled: true
valkyrie:
  fullnameOverride: valkyrie
  enabled: true
  replicaCount: 1
odo:
  enabled: true
