replicaCount: 1

image:
  repository: smartcitiesdata/andi
  tag: development
  pullPolicy: Always

monitoring:
  targetPort: 9002

redis:
  host: redis.external-services
  password: ""

strimzi:
  kafka:
    brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80

secrets:
  live_view:
    enable: true
    value: "devonlyenablefalseanddefineoutofsourceinprod"

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  securityGroups: ""
  certificateARN: ""
  dnsZone: "localhost"

resources:
  limits:
    memory: 256Mi
    cpu: 150m
  requests:
    memory: 256Mi
    cpu: 150m

postgres:
  host: "example.com"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"

vault:
  endpoint: http://vault.vault:8200

env:
  auth0_domain: ""
  auth0_client_id: ""
  auth0_audience: ""
