replicaCount: 1

image:
  repository: smartcitiesdata/andi
  tag: development
  pullPolicy: Always

monitoring:
  targetPort: 9002

redis:
  host: redis.external-services
  password: ""

strimzi:
  kafka:
    brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80

secrets:
  live_view:
    enable: true
    value: "devonlyenablefalseanddefineoutofsourceinprod"

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  securityGroups: ""
  certificateARN: ""
  rules:
    - dnsZone: "localhost"
      hostPrefix: "andi"

resources:
  limits:
    memory: 256Mi
    cpu: 150m
  requests:
    memory: 256Mi
    cpu: 150m

postgres:
  host: "example.com"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"

vault:
  endpoint: http://vault.vault:8200

auth:
  jwt_issuer: ""
  auth0_domain: ""
  auth0_client_id: ""

# The root at which documentation pdfs and other artifacts can be found
documentationRoot: ""

# This flag controls whether Andi is deployed in Public mode or not.
# Public mode prevents all access to Curator features for security reasons.
# Can be "private" or "public"
accessLevel: "private"

tolerations:
  - key: example.run.public-worker
    operator: Equal
    value: "true"
    effect: NoExecute