apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      serviceAccountName: discovery-api
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
          - name: PRESTO_URL
            value: {{ .Values.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
          - name: HOST
            value: data.{{ .Values.ingress.rootDnsZone }}
          - name: ALLOWED_ORIGINS
            value: {{ .Values.ingress.rootDnsZone }},{{ .Values.ingress.dnsZone }}
          - name: LDAP_HOST
            value: {{ .Values.ldap.host }}
          - name: LDAP_BASE
            value: {{ .Values.ldap.base }}
          - name: LDAP_USER
            value: {{ .Values.ldap.user }}
          - name: LDAP_ACCOUNT_SUBDN
            value: {{ .Values.ldap.account.subdn }}
          - name: LDAP_PASS
            valueFrom:
              secretKeyRef:
                name: ldap
                key: password
          - name: GUARDIAN_KEY
            valueFrom:
              secretKeyRef:
                name: guardian
                key: secret_key
          - name: HOSTED_FILE_BUCKET
            value: {{ .Values.environment }}-{{ .Values.s3.hostedFileBucket }}
          - name: HOSTED_FILE_REGION
            value: {{ .Values.s3.hostedFileRegion }}
          - name: SECRETS_ENDPOINT
            value: {{ .Values.vault.endpoint }}
