apiVersion: v1
kind: Secret
metadata:
  name: discovery-api-presign-key
type: Opaque
stringData:
  discovery-api-presign-key: {{ .Values.secrets.discoveryApiPresignKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: guardian-secret-key
type: Opaque
stringData:
  guardian-secret-key: {{ .Values.secrets.guardianSecretKey }}
