
kafka:
  # Override these with the addresses of your Kafka brokers 
  pipeline_brokers: incoming-data-broker:9092
  public_brokers: public-kafka-cluster-broker:9092

  strimziCluster: strimzi-cluster
  transformed_topic: topic-to-read-from

redis:
  host: streisand-redis-master

image:
  repository: smartcitiesdata/streisand
  tag: development
  pullPolicy: Always

# defaults to be overridden by user
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
